%pictransform.m illustrate how 1x16384 array is reshaped to 128x128 for SBF
%FPA - LCG 02/26/2018

%1x16384 gets split among three subsets, 32 sets of 4x128.
i = 4;
j = 32;
k = 128;

in_vec = (1:1:16384); %input vector is linear array of integers 0,1,...,16383.
out_array = zeros([k,k]); % preallocate 128x128 array of zeros.
test_array = zeros([k,k]); %same as out_array.

%128x128 array output after reshaping is as follows:

%each 1x128 increments in steps of 4 
% (e.g. 1,5,9,...509, 
%  then 2,6,10,...510, 
%  then 3,7,11,...511,
%  then 4,8,12,...512.) 
%This group = 4*0*128+(1,5,9,...509)...etc.

%Next group starts from 513 or (4*1*128)+(1,5,9,...509) = 513,517,521,...1021
%                         then (4*1*128)+(2,6,10,...510) = 514,518,522,...1022
%                         ....
%                         ....
% repeats all the way to  (4*31*128)+(4,8,12,...512) = 15876, 15880, 15884,...16384

% Synthetically generate the 128x128 output:
for m = 1:j;
    for n = 1:i;
        fours_vec = (k*(m-1)*i)+((1:i:4*k-1)+(n-1));
        out_array((n+((m-1)*i)),:) = fours_vec;
    end
end

% Generate the same array by indexing a 1D array of 1x16384 and, where 
% in_vec = 1,2,3,....,16384, and inserting into an empty 128x128 array:
for m = 1:j;
    for n = 1:i;
        for o = 1:k;
            test_array(((m-1)*i)+n,o) = in_vec(((m-1)*i*k)+(o+((i-1)*(o-1))+(n-1)));
        end
    end
end

%If we did this right, test_array values should equal out_array values
%The boolean output should be a 128x128 array of ones
bool_array = (test_array == out_array);

%Summing over all indices in bool_array should yield 16384, print for user
%verification.
fprintf(1, 'Boolean comparison of synthetically generated\n pic.dll style output array\n Compared with 1x16384-->128x128\n indexed test array = %5.0f\n',sum(sum(bool_array)));

%Contour plot comparison of the two arrays:
figure;
subplot(2,1,1);
imagesc(out_array); title('Synthetically generated 128x128 array mimicking pic.dll reshaping')
subplot(2,1,2);
imagesc(test_array); title('128x128 array generated by indexing 1D vector of 1,2,...16384, to generate pic.dll reshaping')

